### ISSUE TITLE
systems

### ISSUE THREAD

**Issue by RobKVieira** [resnet-us/hers-diagnostic-schema#5]
If there are multiple cooling or heating systems will each show separately? Could have different efficiencies or fuel types.

**Comment by nealkruis** [comment]
@RobKVieira [space heating, space cooling, and water heating outputs](https://github.com/resnet-us/hers-diagnostic-schema/blob/9eb5292aa12f42e357dbecd790147fc67bb617c6/schema/HERSDiagnosticOutput.schema.yaml#L191-L202) are an array of [SystemOutputs](https://github.com/resnet-us/hers-diagnostic-schema/blob/9eb5292aa12f42e357dbecd790147fc67bb617c6/schema/HERSDiagnosticOutput.schema.yaml#L158-L181). Each system output in this array has its own fuel type and efficiency.

The current example doesn't illustrate this, since there is only one system.

**Comment by RobKVieira** [comment]
Thought that might be the case. Thanks
